site_name: FLAKE Documentation
site_description: Documentation of the QA/QC processes in Datalakes
site_url: https://epfl-enac.github.io/limnc-flake-documentation/

repo_name: EPFL-ENAC/limnc-flake-documentation
repo_url: https://github.com/EPFL-ENAC/limnc-flake-documentation

theme: 
  name: material
  palette:
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - panzoom:
      full_screen: true
      always_show_hint: true
      include_selectors:
        - "img"


nav: 
  - 'Home': index.md
  - 'Roles': roles.md
  - 'Overview of QA/QC': QC.md
  - 'Datasets': datasets.md
  - 'Guides':
    - 'Overview': guides/index.md
    - 'Reporting a QC issue': guides/reporting.md
    - 'Managing QC issues': guides/management.md
    - 'Assigning a data curator/advisor': guides/assignment.md
    - 'Merging QC issues': guides/merging.md
    - 'Modifying the automated L1 QA': guides/QA_json.md
    - 'Managing roles in the instrument repository': guides/roles.md
    - 'Reporting missing feature or code issue': guides/bugs.md
    - 'Updating the documentation': guides/updating_docs.md

  - 'Development':
    - 'events.csv': dev/maintenance.md
